# config.yaml
training:
  min_training_size: 1000
  fail_on_missing_columns: true
  max_iter: 1000
  random_state: 42


data:
  required_columns:
    - Age
    - Rating
    - Positive Feedback Count
    - Division Name
    - Department Name
    - Class Name
    - Recommended IND
